class JointConstants:
    PERSON1 = "person1"
    PERSON2 = "person2"
    X = "x"
    Y = "y"
    GAZE = "gaze"
    LEFT_EYE = "leftEye"
    RIGHT_EYE = "rightEye"
    MOUTH = "mouth"
    CENTRE = "centre"
    HALFSIZE = "halfsize"
    TALKING = "talking"
    TIME_END = "timeEnd"
    TIME_START = "timeStart"
    TYPE = "type"
    MISSING = "missing"
    EXTRA_INFO = "extraInfo"
    FPS = "fps"
    DATA = "data"
    OUT = "out"


class ClusterConstants(object):
    PERSON_1 = "person1"
    PERSON_2 = "person2"
    X = "x"
    Y = "y"
    AVG_FACE_HEIGHT = "avgFaceHeight"
    EXTRA_FACE_SPACE_RATIO = "extraFaceSpaceRatio"
    AVG_FACE_WIDTH = "avgFaceWidth"
    DESIRED_FACE_WIDTH = "desiredFaceWidth"
    FACE_KMEANS = "faceKmeans"
    K = "k"
    COUNTS = "counts"
    CENTROIDS = "centroids"
    OUT_COUNT = "outCount"
    IN_COUNT = "inCount"


class UsableConversationConstants():
    MAIN = "main"
    NUMBER = "number"
    PERSON1 = "person1"
    PERSON2 = "person2"
    FACE_CLUSTERS = "faceClusters"
    OTHER_PERSON_CLUSTERS = "otherPersonClusters"
    CONVERSATIONS = "conversations"

class ReadableConvMetadataConstants():
    AT_HIGH = "person at high"
    AT_LOW = "person at low"
    PERSON1 = "person1"
    PERSON2 = "person2"
    PERSON_1_AT_PERSON_2_PERCENTAGE = "person 1 at person 2 ratio"
    PERSON_2_AT_PERSON_1_PERCENTAGE = "person 2 at person 1 ratio"
    FILE_NAME = "file name"
    DATA = "data"