class MdpConsts:

    NONE = 0
    H_AT_L = AATB = 1
    L_AT_H = BATA = 2
    MUTUAL = 3

    LIST_OF_STATES = [NONE, H_AT_L, L_AT_H, MUTUAL]

    STATE_TO_NONE = 0
    STATE_TO_H_AT_L = 1
    STATE_TO_L_AT_H = 2
    STATE_TO_MUTUAL = 3

    LIST_OF_ACTIONS = [STATE_TO_NONE, STATE_TO_H_AT_L, STATE_TO_L_AT_H, STATE_TO_MUTUAL]
